version: '3'

services:
  # Backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      PORT: 80
      DB_HOST: skillmatchesai1.clys68qy6l9q.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Barbie1620
      DB_NAME: skillmatchesai1
      DB_SSL: "false"
      JWT_SECRET: your-secret-key-change-in-production
      JWT_EXPIRES_IN: 1d
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/package.json:/usr/src/app/package.json
      - ./backend/tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
    restart: unless-stopped

  # PgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@skillmatchesai1.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    restart: unless-stopped