FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies, including ts-node-dev globally
RUN npm install && npm install -g ts-node-dev

# Copy source code
COPY . .

# Build application
RUN npm run build

# Expose the port your app runs on
EXPOSE 80

# Run the application
# Change this to use the built version instead of development mode
CMD ["npm", "run", "start"]