name: Event Action 1

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  workflow_dispatch:

env:
  myPass: 1234

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Test Step
        run: echo "🧪 Skipping actual tests for now."

  build:
    runs-on: ubuntu-latest
    environment: testing
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Debug Scripts
        run: npm run

      - name: Build Code
        run: npm run build --if-present

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Get Build Files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./frontend/dist

      - name: Output Contents
        run: ls -R ./dist

      - name: Deploy
        id: deploy
        uses: ./.github/actions
        with:
          bucket: skillmatchesai
          dist-folder: ./frontend/dist/skillmatches-ai/browser
          bucket-region: eu-north-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

      - name: Output URL
        run: echo "Live URL:${{ steps.deploy.outputs.website-url }}"
